### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by omrysendik** [NVlabs/PWC-Net#11]
Hi,

I am trying to get the code running.
I compiled and installed everything and believe I passed this stage successfully.
However, I currently receive the following error:
ImportError: /correlation_package/_ext/corr/_corr.so: undefined symbol: __cudaPopCallConfiguration

Any support would be helpful

**Comment by luvegood** [comment]
Could you please provide your cuda version? And what's the output after you compiled the correlation layer?

**Comment by omrysendik** [comment]
**I'm using CUDA9.2**

**After compiling (running the designated bash script):** 
$ bash make_cuda.sh 
Compiling correlation layer kernels by nvcc...
Including CUDA code.
running build
running build_py
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/correlation_package
copying correlation_package/__init__.py -> build/lib.linux-x86_64-3.6/correlation_package
creating build/lib.linux-x86_64-3.6/correlation_package/functions
copying correlation_package/functions/__init__.py -> build/lib.linux-x86_64-3.6/correlation_package/functions
copying correlation_package/functions/corr.py -> build/lib.linux-x86_64-3.6/correlation_package/functions
creating build/lib.linux-x86_64-3.6/correlation_package/_ext
copying correlation_package/_ext/__init__.py -> build/lib.linux-x86_64-3.6/correlation_package/_ext
creating build/lib.linux-x86_64-3.6/correlation_package/modules
copying correlation_package/modules/__init__.py -> build/lib.linux-x86_64-3.6/correlation_package/modules
copying correlation_package/modules/corr.py -> build/lib.linux-x86_64-3.6/correlation_package/modules
creating build/lib.linux-x86_64-3.6/correlation_package/_ext/corr
copying correlation_package/_ext/corr/__init__.py -> build/lib.linux-x86_64-3.6/correlation_package/_ext/corr
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.6/correlation_package._ext.corr._corr.c'
creating build/temp.linux-x86_64-3.6
building 'correlation_package._ext.corr._corr' extension
creating build/temp.linux-x86_64-3.6/build
creating build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/home
creating build/temp.linux-x86_64-3.6/home/omry
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package
creating build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src
gcc -pthread -B /home/omry/anaconda2/envs/py35/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/omry/anaconda2/envs/py35/include/python3.6m -c build/temp.linux-x86_64-3.6/correlation_package._ext.corr._corr.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/correlation_package._ext.corr._corr.o
gcc -pthread -B /home/omry/anaconda2/envs/py35/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/omry/anaconda2/envs/py35/include/python3.6m -c /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr.c -o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr.o
gcc -pthread -B /home/omry/anaconda2/envs/py35/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/omry/anaconda2/envs/py35/include/python3.6m -c /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d.c -o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d.o
gcc -pthread -B /home/omry/anaconda2/envs/py35/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/omry/anaconda2/envs/py35/include/python3.6m -c /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr_cuda.c -o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr_cuda.o
gcc -pthread -B /home/omry/anaconda2/envs/py35/compiler_compat -Wl,--sysroot=/ -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -DWITH_CUDA -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/omry/anaconda2/envs/py35/include/python3.6m -c /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d_cuda.c -o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d_cuda.o
gcc -pthread -shared -B /home/omry/anaconda2/envs/py35/compiler_compat -L/home/omry/anaconda2/envs/py35/lib -Wl,-rpath=/home/omry/anaconda2/envs/py35/lib -Wl,--no-as-needed -Wl,--sysroot=/ -std=c99 build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/correlation_package._ext.corr._corr.o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr.o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d.o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr_cuda.o build/temp.linux-x86_64-3.6/home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d_cuda.o /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr_cuda_kernel.cu.o /home/omry/Dropbox/Third_Degree/TAU/Code/GeomStylTrns/GeomCycGAN/models/correlation_package/correlation_package/src/corr1d_cuda_kernel.cu.o -o build/lib.linux-x86_64-3.6/correlation_package/_ext/corr/_corr.abi3.so
running install
running bdist_egg
running egg_info
writing correlation_package.egg-info/PKG-INFO
writing dependency_links to correlation_package.egg-info/dependency_links.txt
writing requirements to correlation_package.egg-info/requires.txt
writing top-level names to correlation_package.egg-info/top_level.txt
reading manifest file 'correlation_package.egg-info/SOURCES.txt'
writing manifest file 'correlation_package.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/correlation_package
copying build/lib.linux-x86_64-3.6/correlation_package/__init__.py -> build/bdist.linux-x86_64/egg/correlation_package
creating build/bdist.linux-x86_64/egg/correlation_package/functions
copying build/lib.linux-x86_64-3.6/correlation_package/functions/__init__.py -> build/bdist.linux-x86_64/egg/correlation_package/functions
copying build/lib.linux-x86_64-3.6/correlation_package/functions/corr.py -> build/bdist.linux-x86_64/egg/correlation_package/functions
creating build/bdist.linux-x86_64/egg/correlation_package/_ext
copying build/lib.linux-x86_64-3.6/correlation_package/_ext/__init__.py -> build/bdist.linux-x86_64/egg/correlation_package/_ext
creating build/bdist.linux-x86_64/egg/correlation_package/_ext/corr
copying build/lib.linux-x86_64-3.6/correlation_package/_ext/corr/__init__.py -> build/bdist.linux-x86_64/egg/correlation_package/_ext/corr
copying build/lib.linux-x86_64-3.6/correlation_package/_ext/corr/_corr.abi3.so -> build/bdist.linux-x86_64/egg/correlation_package/_ext/corr
creating build/bdist.linux-x86_64/egg/correlation_package/modules
copying build/lib.linux-x86_64-3.6/correlation_package/modules/__init__.py -> build/bdist.linux-x86_64/egg/correlation_package/modules
copying build/lib.linux-x86_64-3.6/correlation_package/modules/corr.py -> build/bdist.linux-x86_64/egg/correlation_package/modules
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/functions/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/functions/corr.py to corr.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/_ext/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/_ext/corr/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/modules/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/modules/corr.py to corr.cpython-36.pyc
creating stub loader for correlation_package/_ext/corr/_corr.abi3.so
byte-compiling build/bdist.linux-x86_64/egg/correlation_package/_ext/corr/_corr.py to _corr.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_package.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_package.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_package.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_package.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying correlation_package.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
correlation_package._ext.corr.__pycache__._corr.cpython-36: module references __file__
creating 'dist/correlation_package-0.1-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing correlation_package-0.1-py3.6-linux-x86_64.egg
removing '/home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/correlation_package-0.1-py3.6-linux-x86_64.egg' (and everything under it)
creating /home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/correlation_package-0.1-py3.6-linux-x86_64.egg
Extracting correlation_package-0.1-py3.6-linux-x86_64.egg to /home/omry/anaconda2/envs/py35/lib/python3.6/site-packages
correlation-package 0.1 is already the active version in easy-install.pth

Installed /home/omry/anaconda2/envs/py35/lib/python3.6/site-packages/correlation_package-0.1-py3.6-linux-x86_64.egg
Processing dependencies for correlation-package==0.1
Searching for cffi==1.11.5
Best match: cffi 1.11.5
Adding cffi 1.11.5 to easy-install.pth file

Using /home/omry/anaconda2/envs/py35/lib/python3.6/site-packages
Searching for pycparser==2.18
Best match: pycparser 2.18
Adding pycparser 2.18 to easy-install.pth file

Using /home/omry/anaconda2/envs/py35/lib/python3.6/site-packages
Finished processing dependencies for correlation-package==0.1

**Comment by omrysendik** [comment]
Forgot to mention that I needed to manually copy the newly compiled _corr.so file to the right folder.

**Comment by luvegood** [comment]
Thanks. When using the correlation package (and eventually developing the implementation) we are using CUDA-8.0 + python 2.7. I saw you are using anaconda, perhaps it's worth trying to specify the correct environment this way, and give it another try.

**Comment by omrysendik** [comment]
Any idea where/which file refers to this symbol (__cudaPopCallConfiguration)?
I need a hint to start from...

**Comment by luvegood** [comment]
I don't have any intuitions. From similar issues for other github projects, the issue seems to be related to cuda versions. For example: (1) https://github.com/uber/horovod/issues/274  (2) https://github.com/jwyang/faster-rcnn.pytorch/issues/190.

**Comment by sniklaus** [comment]
You could try using my PyTorch reimplementation that matches the official Caffe version and uses CuPy which allows it to work easier out of the box: https://github.com/sniklaus/pytorch-pwc

**Comment by omrysendik** [comment]
@sniklaus your implementation works like a charm!
A huge thanks!!!

**Comment by luvegood** [comment]
Our pytorch code was developed prior to the code release date of PWC-Net, in the latest commit https://github.com/NVlabs/PWC-Net/commit/fc6ebf9a70a7387164df09a3a2070ba16f9c1ede we modified pytorch model to match the caffe version. 

For the issue of importing correlation layer, you could either use Simon's code or use a cuda version that is prior to CUDA 9.0. This code was also develped long ago.
