### ISSUE TITLE
"cudaCheckError() failed: a PTX JIT compilation failed" 

### ISSUE THREAD

**Issue by lr87** [NVlabs/PWC-Net#17]
Thanks for your work!

I have installed the correlation package. Then I run the test.py and it got: 
"cudaCheckError() failed: a PTX JIT compilation failed"

Since the correlation package is necessary for the PWC-Net, I can't go on with the rest. 
Can you give some idea to solve this issue? I use GTX 1080 and CUDA 9.1. 
Thanks a lot!

**Comment by luvegood** [comment]
Can you try using CUDA 8.0?

**Comment by lr87** [comment]
Hi! Thanks for your advice. I tried but got the same error. @luvegood

**Comment by luvegood** [comment]
I don't have further intuitions. You could check another pytorch implementation at https://github.com/sniklaus/pytorch-pwc, this code is using CuPy for the correlation layer, so hopefully won't cause such problems. Their network structure is the same as this official code.

**Comment by lr87** [comment]
Thank you! I'll have a try.

**Comment by deqings** [comment]
Note that our code was developed using **Python 2.7** & PyTorch 0.2 & CUDA 8.0. It would be good to check the other two settings too.

**Comment by hzk7287** [comment]
Hi, I meet the same problem . You can update your GCC-version to have a try. I update to gcc4.9.
