### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by TusharNimbhorkar** [NVlabs/PWC-Net#19]
Hi

Can you comment on the how much time it took you guys to train the model from scratch? And what configuration you have in terms of GPU power? 

Thanks

**Comment by deqings** [comment]
You can refer to Table 7 in our paper https://arxiv.org/pdf/1709.02371.pdf for the training time using a single NVIDIA Pascal TitanX GPU.

**Comment by TusharNimbhorkar** [comment]
Thanks for the reply

**Comment by JiamingSuen** [comment]
I wonder if the training time mentioned in Table 7 includes all the dataset training(Chairs + Things + Sintel)? or just on FlyingChairs, thanks!

**Comment by ChaoyiXie** [comment]
`//.flo file to remap Mat
//String addr: the .flo file name
// cv::Mat flo: the Mat that can use function remap in opencv: cv::remap(img1,img2,flo,cv::Mat(),1);
void floread(cv::String addr, cv::Mat &flo) {
	std::ifstream fin(addr, std::ios::binary);
	char buffer[sizeof(float)];
	fin.read(buffer, sizeof(float));
	float tar = ((float*)buffer)[0];
	if (tar != TAR) {
		fin.close();
		return;
	}
	fin.read(buffer, sizeof(int));
	int width = ((int*)buffer)[0];
	fin.read(buffer, sizeof(int));
	int height = ((int*)buffer)[0];
	//std::cout << width << "\t" << height << std::endl;
	flo = cv::Mat(cv::Size(width, height), CV_32FC2);
	for (int i = 0; i < height; i++) {
		for (int j = 0; j < width; j++) {
			if (!fin.eof()) {
				float * data = flo.ptr<float>(i, j);
				fin.read(buffer, sizeof(float));
				data[0] = j + ((float*)buffer)[0];
				fin.read(buffer, sizeof(float));
				data[1] = i + ((float*)buffer)[0];
			}
		}
	}
	fin.close();
}`
the code transform from .flo file to remap Matrix,so that  I get the remap image ,but it's not very good ,do you know why??

**Comment by lelelexxx** [comment]
> I wonder if the training time mentioned in Table 7 includes all the dataset training(Chairs + Things + Sintel)? or just on FlyingChairs, thanks!

Hi, Did you figure it out?  I prefer that the training time including training in chairs + things. Because all the model of Sintel,kitti2012,kitti2015 are finetuned from it.
