### ISSUE TITLE
self.deconv2 in PyTorch version is not being used

### ISSUE THREAD

**Issue by sniklaus** [NVlabs/PWC-Net#2]
Thank you for sharing your work, it is greatly appreciated!

I just wanted to point out that `self.deconv2` in the PyTorch version is not being used / referenced.

https://github.com/NVlabs/PWC-Net/blob/a17ec5b21f0ff8f93a303de651c9749914159809/PyTorch/models/PWCNet.py#L116

**Comment by lxtGH** [comment]
Also，you should convert all dd[0] (which is numpy array )into int type

**Comment by deqings** [comment]
Thank you both for your comments and suggestions. We have modified PWCNet.py accordingly.

Best regards,
Deqing
