### ISSUE TITLE
Training epochs, and epoch size.

### ISSUE THREAD

**Issue by jangho2001us** [NVlabs/PWC-Net#21]
Hi,

When training your code, you might add some hyperparameters such as epochs and epoch size.
I am also training my own model and compare the results with yours.
Here, I wonder which value  (epochs and epoch size) you used on your model training.
I think the results depend on the hyperparameters you selected.
Could you let me know hyperparameters?

Thanks

**Comment by deqings** [comment]
You can refer to the training protocol in Caffe for the hyperparameter setting to train on FlyingChairs.
