### ISSUE TITLE
The input channel of convolutions in the optical flow estimator class

### ISSUE THREAD

**Issue by Simpatech-app** [NVlabs/PWC-Net#23]
Thanks for such a great work. 

I checked the code and paper, I cannot figure out one point. I would be very thankful if you can clarify it for me.
How did you define the number of the in channel input for the the optical flow decoder? why the input channel of the next level is not equal to output channel of previous layer?
what is the logic behind these number?
I really appreciate your support.

**Comment by deqings** [comment]
Thanks for your interest in our work. 

That's a great question. Intuitively, we would like to gradually reduce the number of feature channels before finally mapping them to the 2-channel optical flow. However, we don't have theoretical justifications for this empirical approach. Using the same number of output as previous layers is likely to work as well, albeit with more parameters/computation. You are more than welcome to test the alternative.

Best regards,
Deqing
