### ISSUE TITLE
Is the provided model finetuned on KITTI

### ISSUE THREAD

**Issue by MightyChaos** [NVlabs/PWC-Net#26]
Could the author specify the training set used for the provided model, i.e. [pwc_net.pth.tar](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/pwc_net.pth.tar). Aside from the flying chair for pretraining, I guess it has also been finetuned on both sintel and KITTI?

**Comment by luvegood** [comment]
This specific model is fine-tuned on Sintel dataset, and this pytorch model is ported from the learned caffe model.

**Comment by deqings** [comment]
The provided model has been fine-tuned using Sintel, KITTI 2015, and HD1K data and corresponds to PWC-Net_ROB model in these benchmarks.
