### ISSUE TITLE
some issues and corresponding corrections in Caffe-Project

### ISSUE THREAD

**Issue by popsheng** [NVlabs/PWC-Net#3]
two  issues and corresponding corrections:

- visualization
1. change `from flow_io import flow_read_uv` to `from flow_io import flow_read`
2. change `I_flow = Image.fromarray(viz_flow(uv[0,:,:], uv[1,:,:]))` to `I_flow = Image.fromarray(viz_flow(uv[0], uv[1]))`

- compile
error: `Unknown Engine error`
see [link](https://github.com/bqlabs/flownet/issues/1)

one question: where is  run_rob_test.py in the 3rd step (testing)

**Comment by deqings** [comment]
Dear popsheng,

Thank you for the comments. I have fixed the visualization issue and run_rob_test.py will be added very soon.

For the compile issue,  did you add cuDNN to your environment/in your compilation file? the cuDNN engine should run faster than the Caffe engine.

Best regards,
Deqing
