### ISSUE TITLE
Correlation operation in cost volume layer

### ISSUE THREAD

**Issue by MrRoboticist** [NVlabs/PWC-Net#31]
Hi,

My question is about the exact correlation operation used in the cost volume layer. In the paper, the operation is defined as:
![image](https://user-images.githubusercontent.com/42276613/45384796-4dc01a00-b60f-11e8-95cd-20a482543515.png)

where the dot product of the 2 feature vectors is divided by the length `N` of the feature vectors. However, in the code for the cost volume layer the dot product has been scaled by `sumelems` which has been defined as `kernel_size*kernel_size*bottomchannels` in [one place](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/external_packages/correlation-pytorch-master/correlation-pytorch/correlation_package/src/corr_cuda_kernel.cu#L119) and as `(kernel_radius*2+1)*(kernel_radius*2+1)*bottomchannels` in [another](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/external_packages/correlation-pytorch-master/correlation-pytorch/correlation_package/src/corr_cuda_kernel.cu#L268). I'm guessing that the `kernel_size` is the same as `2*kernel_radius+1`, but I am not sure.

I am implementing the layer in another framework and hence wanted to clarify this: the dot product of the 2 feature vectors is finally divided by `(2*d+1)*(2*d+1)*N`, where `d` is the kernel radius and `N` is the number of channels in the feature map. Is this correct?

**Comment by deqings** [comment]
In our implementation, the kernel_radius is set to be 0 and so N in equation (2) refers to the number of channels. If you use a non-zero kernel_radius, you need to divide by (2*d+1)*(2*d+1)*N.

**Comment by MrRoboticist** [comment]
Ah, I see.

So you have written code for the correlation operation as the more general patch-wise matching operation. However, for your experiments, you have set the radius of this patch to be 0, in other words only performing pixel-wise matching. Makes sense.

I suppose I confused `kernel_radius` (which is the radius of the image patch around the reference pixel used for matching) to be `max_displacement` (which is the maximum distance away that we compute the match).
