### ISSUE TITLE
proc_images output does not match reference

### ISSUE THREAD

**Issue by achalddave** [NVlabs/PWC-Net#32]
I ran [`proc_images.py`](https://github.com/NVlabs/PWC-Net/blob/6ebd42a9f23a3dc75c8992e5f9f6937e210b27fc/Caffe/proc_images.py) in the `Caffe/` subdirectory, but the output flow does not match the provided reference flows.

The forward flow ("`frame_0010_forward.png`") that was output when I ran `proc_images.py`:
![image](https://user-images.githubusercontent.com/1168881/45516147-3badbb00-b778-11e8-935a-558c75a22c21.png)

The reference image:
![image](https://user-images.githubusercontent.com/1168881/45516200-5f710100-b778-11e8-9ce8-0aa7acbb17d3.png)

I used [OpticalFlowToolkit](https://github.com/liruoteng/OpticalFlowToolkit/tree/b09cc889fa93493018b94df63141990cc9692dd3) to visualize the flows, but the raw .flo files also differ. I compiled flownet2 from commit [9eed763](https://github.com/lmb-freiburg/flownet2/tree/9eed763789c06fa5f44e7af79078c0446a82bfc6), and PWC-net at commit [6ebd42a](https://github.com/NVlabs/PWC-Net/tree/6ebd42a9f23a3dc75c8992e5f9f6937e210b27fc).

Am I running the wrong model? The reference seems a bit cleaner than what I get on my machine.

**Comment by bkvie** [comment]
The reference is the ground truth

**Comment by achalddave** [comment]
Yes I tried both the pretrained weights. I would be surprised if the reference is the groundtruth, given that the README says to "Please compare your results with ./tmp/reference_frame_0010_forward.flo and ./tmp/reference_frame_0011_backward.flo."...

**Comment by deqings** [comment]
The reference is not the ground truth. Very likely the difference was caused by different software/hardware environments, which, unfortunately, we won't be able to help debug. Can you compute the average EPE on Sintel training and see whether the average numbers are close to our reported ones?
