### ISSUE TITLE
About the upfeature

### ISSUE THREAD

**Issue by jiujing23333** [NVlabs/PWC-Net#33]
A great work! I have a doubt when reading your code.
I note that you employ several deconv layer to obtain upfeature with 2 channels. What  motivated you to do this?  Have you tried a thicker upfeature(channels number >2)?
Thanks!

**Comment by deqings** [comment]
It's an empirical setting. We tested 16 and 32 but didn't see obvious improvement. Removing the upfeature slightly hurts the performance.
