### ISSUE TITLE
Failed to compile correlation with pytorch 0.4.1 cuda 9.0

### ISSUE THREAD

**Issue by xqterry** [NVlabs/PWC-Net#34]
os: ubuntu 17.10
cuda: 9.0
pytorch: 0.4.1.post2

tried to run make_cuda.sh got following error:
```
correlation-pytorch/correlation_package/src/corr_cuda.c:23:27: 
error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
     int batchSize = input1->size[0];
```

**Comment by bkvie** [comment]
try with cuda 8.0

**Comment by JCBrouwer** [comment]
Was able to compile with cuda 9.0 & cudnn 7.0 as soon as I downgraded to pytorch 0.4.0.

According to [this issue](https://github.com/pytorch/pytorch/issues/8483#issuecomment-411104356) 0.4.1 broke a lot of cuda extensions.

**Comment by luvegood** [comment]
You might want to check the readme of the pytorch code first: The code was developed using Python 2.7 & PyTorch 0.2 & CUDA 8.0. You can test the code by using anaconda to set up the environment properly.

**Comment by sniklaus** [comment]
You could give this implementation a try: https://github.com/sniklaus/pytorch-pwc

**Comment by JCBrouwer** [comment]
@sniklaus Amazing!

Runs perfectly for me with specs as mentioned above.

**Comment by nankeermeng** [comment]
int batchSize = THCudaTensor_size(state,input1,0); replace  int batchSize = input1->size[0];
but I met another problem:Anaconda3/yes/compiler_compat/ld: cannot find -lpthread
Anaconda3/yes/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1.
and I cannot solve it

**Comment by luvegood** [comment]
@nankeermeng The pytorch code was developed using Python 2.7 & PyTorch 0.2 & CUDA 8.0, have you configured the environment correctly? If you still experience troubles, you may refer to the code written by @sniklaus the network structure is the same.

**Comment by nankeermeng** [comment]
thank you @luvegood , i solve the problem that it can not find -lpthread, but I met the same problem as CuDNN Error #37 @taylover-pei

**Comment by xqterry** [comment]
@sniklaus Thanks.

**Comment by kvara** [comment]
I'm trying to run code without gpu , is it possible?

**Comment by luvegood** [comment]
@kvara the implementation of correlation layer is implemented in CUDA, so it may require some extra work to get the code to work in cpu.
