### ISSUE TITLE
Whether the model can detect subtle movement

### ISSUE THREAD

**Issue by taylover-pei** [NVlabs/PWC-Net#35]
Congratulations, you have done a great job.
I have a question about whether the model can detect subtle movement?  For example, in the face recognition system, the movement of the face in front of the camera within 1 second is very subtle. So, whether this model can detect such subtle movement?
Thank you very much. Looking forward to your reply.

**Comment by bkvie** [comment]
Try it out ... 
In script_pwc.py just change the image path

**Comment by deqings** [comment]
I also recommend trying it out. 
Besides, if you are interested in such subtle motion, you may consider collecting some ground truth, such as from synthetic data, and re-train the network for your particular application.
