### ISSUE TITLE
Can't find corr_cuda_forward

### ISSUE THREAD

**Issue by ZeeshanNadir** [NVlabs/PWC-Net#39]
Greetings,
When I try to repeat this model, I can't find the implementation of "corr_cuda_forward". Where is this defined?
Thanks

**Comment by sniklaus** [comment]
You can find its implementation in [corr_cuda.c](https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/external_packages/correlation-pytorch-master/correlation-pytorch/correlation_package/src/corr_cuda.c).

https://github.com/NVlabs/PWC-Net/blob/6ebd42a9f23a3dc75c8992e5f9f6937e210b27fc/PyTorch/external_packages/correlation-pytorch-master/correlation-pytorch/correlation_package/src/corr_cuda.c#L7
