### ISSUE TITLE
Much Memory needing for the caffe version

### ISSUE THREAD

**Issue by letatanu** [NVlabs/PWC-Net#4]
Thank you so much for sharing your code. 
I have an issue about running the caffe version.
My PC has NVIDIA 1080 Ti.
When I run it on a pair of images 1080p, it raised this error:

> syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

Does it need that much memory?
Thank you.

**Comment by deqings** [comment]
Very likely 11G memory is insufficient for 1080p (1920x1080). For reference,  HD1K resolution image pairs (2560x1080) caused out of memory error on TitanX with 12G memory. we needed to use NVIDIA Volta 100 with 16G memory. 

You could downsample the image by half as input to the network and then upsample and rescale the output flow to the original resolution. The performance loss is about 10%.
