### ISSUE TITLE
Recompute_mean in Test Phase

### ISSUE THREAD

**Issue by sunshinezhe** [NVlabs/PWC-Net#40]
Hi Author,

very impressive work!

When I check the code, I found there still recompute mean when testing. 

Is this mean you use the statistical characteristics of test dataset?

**Comment by deqings** [comment]
Our experience is that "recompute_mean: 1000" actually has no effect during the test. You could modify the data_augmentation_layer.cu to output the actual mean used (0 in our past experiment).
