### ISSUE TITLE
how can i use corr1d with single direction for disparity estimation?

### ISSUE THREAD

**Issue by CHZhu940222** [NVlabs/PWC-Net#41]
how can i use corr1d with single direction for disparity estimation?
int corr1d_cuda_forward(THCudaTensor *input1,
                      THCudaTensor *input2,
                      THCudaTensor *rbot1,
                      THCudaTensor *rbot2,
                      THCudaTensor *output,
                      int pad_size,
                      int kernel_size,
                      int max_displacement,
                      int stride1,
                      int stride2,
                      int corr_type_multiply
                      //single_direction=0 
)
best and thanks!

**Comment by deqings** [comment]
Sorry for the very late reply. You may check the dispnet that uses this layer (https://lmb.informatik.uni-freiburg.de/resources/binaries/dispflownet/dispflownet-release-1.2.tar.gz)
