### ISSUE TITLE
meaning of scaling factor 

### ISSUE THREAD

**Issue by hogeman2** [NVlabs/PWC-Net#45]
Hi, Nice work and your code works well Thanks!

Just a simple question about training and testing

1. Is there any reason why you multiply (0.65 1.25 2.5 5.0) to flow not (1.0 2.0 4.0 8.0). ( maybe this parameter come from flownet implementaion?)

2. Can  model predict flow larger than trained resolution images? ( eg Full HD size )

waiting your reply Thanks!

**Comment by luvegood** [comment]
1. take the example of multiplying the last layer by 5.0 as an example, the output of the flow is 1/4 in height and width, and in training we divide the flow by 20. Therefore, we need to multiply by 20/4 = 5.
2. you may have a try by fine tuning pwcnet on your own HD dataset, and take a look at the output.

**Comment by deqings** [comment]
2.  The HD1K data are of higher resolution (2560x1080) than the training data and the trained model works on the HD1K data. The only constraint is that you need a GPU with large memory (>= 16G), such as Volta 100, to run on full HD size.
