### ISSUE TITLE
Regarding the number of epoch

### ISSUE THREAD

**Issue by Simpatech-app** [NVlabs/PWC-Net#47]
Dear Author
It is very impressive work.
I can not find any refer either in paper or code for number of epoch, which you considered for training. I appreciate if you mention how many epoch did you use for training purposes.

Thanks in advance

**Comment by deqings** [comment]
Please refer to the implementation details and the cited references in section 4 of this paper https://arxiv.org/pdf/1809.05571.pdf. The number of iterations is for Caffe training. You need to convert them to epoch numbers for other frameworks.
