### ISSUE TITLE
jbarker-nvidia/pytorch-correlation does not exist

### ISSUE THREAD

**Issue by NimSed** [NVlabs/PWC-Net#49]
Hi there.
While building the external correlation package, I see that https://github.com/jbarker-nvidia/pytorch-correlation does not exist. Am I missing something obvious?

Thanks!

**Comment by luvegood** [comment]
Could you post your installation steps and error messages? It's very strange that you encounter this error. Alternatively, we have provided a simple installation scripts using anaconda, see the readme file for detail: https://github.com/NVlabs/PWC-Net/tree/master/PyTorch

**Comment by NimSed** [comment]
Thanks for the quick reply.
Well I am trying to get it running with python3 , etc. So a bit of a customized run. But this problem (I think) has nothing to do with that:
When trying to build the external correlation package manually (as also suggested in the README file), I have to run setup.py which is located in:
`PWC-Net/PyTorch/external_packages/correlation-pytorch-master/correlation-pytorch/setup.py`
Inside this script, the url for the package refers to:
`url="https://github.com/jbarker-nvidia/pytorch-correlation"`
But this repository does not exist on GitHub (any more?) -- also when you try to open it with a browser.

Again, I could be doing something totally wrong!
This is the error setup.py spits out:
`distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('cffi>=1.0.0')`

Best,

**Comment by NimSed** [comment]
BTW, cffi is already installed with pip, both for python2 and 3. That's why I assume the script is trying to fetch something from that non-existing repository..

**Comment by luvegood** [comment]
@NimSed we mentioned in the readme file that it can only work with python2, so in your case, a easier solution is to use anaconda, which we provide a very detailed script on how to set up the environment. Once again, please try the installation script described in https://github.com/NVlabs/PWC-Net/tree/master/PyTorch

**Comment by NimSed** [comment]
Thanks for your suggestion. But installing Anaconda is not an option for me right now.

Actually I could easily build and run your network with my own settings (python3, latest pytorch), just replacing the provided correlation package with another one. So, you may want to double check it in future.

**Comment by luvegood** [comment]
Thanks. Would you mind specifying which other correlation package you are
using now, so that people can use it for reference.

**Comment by rsokl** [comment]
@NimSed can you indicate which correlation package you used?

**Comment by NimSed** [comment]
@luvegood , @rsokl 
Apologies for the late reply.
I used the one used by sniklaus here: https://github.com/sniklaus/pytorch-pwc.git
Of course I needed to apply minor modifications (1-2 code lines) in PWC-Net to make them work together. (Unfortunately right now I do not have the modified code)

Hope it helps

**Comment by Enoimpih** [comment]
When I tried to build the correlation layer, I encountered an error:
$ python setup.py build install
error in correlation_package setup command: 'D:/build.py:ffi_variable' must be of the form 'path/b
uild.py:ffi_variable'
I have no idea what to do.
