### ISSUE TITLE
Unexpected key "deconv2.weight" in state_dict

### ISSUE THREAD

**Issue by letatanu** [NVlabs/PWC-Net#5]
I'm trying to run the pytorch version of PWC-net. I run it in Python 2.7.15, Pytorch 0.2.0_4.
When I run the demo code:

`python script_pwc.py './data/frame_0010.png' './data/frame_0011.png' './tmp/frame_0010.flo'
`

It returned this error:

> KeyError: 'unexpected key "deconv2.weight" in state_dict'

Do you know how to fix it?
Thank you.

**Comment by PeiliangLi** [comment]
use **pwc_dc_net_old** instead **pwc_dc_net** can solve this problem

**Comment by letatanu** [comment]
Thank you. I've solved this problem.
