### ISSUE TITLE
Difference between Flowwarp Layer and Warp Layer

### ISSUE THREAD

**Issue by AlanZhang1995** [NVlabs/PWC-Net#54]
Hi, I have a small question about the caffe version of your PWC-net.
As shown in readme.md, this version is based on flownet2.0. However, you re-implemented warp layer as 'warp_layer.cu'. I also noticed that flownet2.0 had a similar implemented layer called  'flow_warp_layer.cu' (https://github.com/lmb-freiburg/flownet2/blob/master/src/caffe/layers/flow_warp_layer.cu) . After reading codes, i found both warped images/features using bilinear interpolation and i wonder what's the difference?
Thank you!

**Comment by deqings** [comment]
You are right that both implement the bilinear interpolation operation. We started the project based on FlowNet1.0 and implemented the warp layer by ourselves. When FlowNet2.0 was released, we checked that the two implementations have very close behaviors. We kept using our own implementation to be consistent with our previously trained models.
