### ISSUE TITLE
About GPU memory cost during training

### ISSUE THREAD

**Issue by AlanZhang1995** [NVlabs/PWC-Net#57]
Hi, i meet a problem during training.
According to the paper, you use patch size 448*384 batch size 8 and  patch size 768*384 batch size 4 to training PWCNet on FlyingChairs dataset. However, when i run caffe version myself, i find it still out of memory on single 1080Ti with patch size 256*256 and batch size 4. So i wonder what and how many GPUs are used in the training phase.
Thank you

**Comment by luvegood** [comment]
PWCNet is very memory-friendly, and the training set has images with much larger sizes than 256x256. Could you please double check if there are other programmes that are consuming GPU memory in your machine?

**Comment by deqings** [comment]
For training with a cropping patch size 448*320 and batch size 8, the GPU memory consumption is less than 6G. A single 1080Ti should be sufficient. As suggested by luvgood, please check whether other programs are consuming your GPU memory using nvidia-smi.
