### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by shanyuhu** [NVlabs/PWC-Net#6]
Could you please provide the model weights which pretrained on Flying Chair and finetuned on flyingthings3D? 
Thanks~

**Comment by deqings** [comment]
I have added the model for the Caffe version at Caffe/model/pwc_net_chairs_things.caffemodel.

Deqing

**Comment by shanyuhu** [comment]
@deqings , thanks  a lot for your update. Could you also provide a pytorch version of the model weights? 
Looking forward to your reply!

**Comment by sniklaus** [comment]
You can find a PyTorch version that uses these weights here: https://github.com/sniklaus/pytorch-pwc

**Comment by shanyuhu** [comment]
@sniklaus thanks for your nice work.

**Comment by luvegood** [comment]
The pretrained pytorch model is provided in the latest commit: https://github.com/NVlabs/PWC-Net/commit/9808cf653bc5331962074f51db3d57f12695dbbd
