### ISSUE TITLE
Generated .flo files for visualization

### ISSUE THREAD

**Issue by tianbartek** [NVlabs/PWC-Net#66]
I use the provided model (pwc_net.pth.tar), and execute python script_pwc.py '....../alley_1/frame_0001.png'  '....../alley_frame_0002'  '....../tmp/frame0001.flo'.  Then visualize the .flo file, but the results are very strange and the results are different each time.  I have been stuck here. Has anyone encountered this situation? Can you give me some advice?
![image](https://user-images.githubusercontent.com/29172558/53396351-328b7000-39df-11e9-93c0-9400999149dc.png)

**Comment by zgxsin** [comment]
Hi, @tianbartek , I am want to visualize the .flo file. Could you tel me how to visualize it? Someone told me to use the code: https://github.com/tomrunia/OpticalFlow_Visualization. However, i got this error: 
> OSError: Failed to interpret file './out.flo' as a pickle
Do you have any idea? Thank you!

**Comment by tianbartek** [comment]
Hi

I used two different ways to visualize. The first way is to use MATLAB. The
second way is to use Python, similar to the link you gave. But I have not
encountered the problem similar to yours. You can also use other methods,
such as MATLAB.

zgxsin <notifications@github.com> 于2019年2月27日周三 下午9:19写道：

**Comment by tianbartek** [comment]
> Hi, @tianbartek , I am want to visualize the .flo file. Could you tel me how to visualize it? Someone told me to use the code: https://github.com/tomrunia/OpticalFlow_Visualization. However, i got this error:
> 
> > OSError: Failed to interpret file './out.flo' as a pickle
> > Do you have any idea? Thank you!

**Comment by zgxsin** [comment]
@tianbartek Thank you! I solved the problem. Changing the read method works. The result of the optical flow is a binary file instead of a pickle.

**Comment by tianbartek** [comment]
Can you do me a favor? I want to ask you some other things, but I can't
find your email address. If you are convenient, can I email you or contact
me directly (tianbartek@gmail.com)

zgxsin <notifications@github.com> 于2019年2月28日周四 下午4:31写道：

**Comment by ilinii** [comment]
**Hello !** 
To anyone who might encounter such a problem in the future, just use the module **_flowiz_** in python, easy and short to implement ! Thanks for reading this.
