### ISSUE TITLE
Frame per second

### ISSUE THREAD

**Issue by efyphil** [NVlabs/PWC-Net#77]
Hello, thank you for your work. I have a problem with network uptime. The article stated that the speed was 35 fps, but it takes about 0.71 seconds to test for a couple of images. Perhaps it is a problem of implementation on pytorch?

**Comment by Ecalpal** [comment]
@efyphil The FPS is depend on your input image size and hardware..

**Comment by luvegood** [comment]
Also, have you ignored the model loading time?

**Comment by efyphil** [comment]
I've taken all these comments into account, but I still get more time than stated, maybe it's time for caffe2 implementation
