### ISSUE TITLE
Confidence per pixel

### ISSUE THREAD

**Issue by hoopoe** [NVlabs/PWC-Net#82]
Hey, 
Is it possible to get confidence for each pixel of output? Or a kind of correlation on pixel lvl
Thanks

**Comment by deqings** [comment]
Hi,

PWC-Net has no confidence measure. You may refer to the following papers for uncertainty prediction
http://openaccess.thecvf.com/content_cvpr_2018/papers/Gast_Lightweight_Probabilistic_Deep_CVPR_2018_paper.pdf
https://lmb.informatik.uni-freiburg.de/Publications/2018/ICKMB18/ 

Best,
Deqing

**Comment by hoopoe** [comment]
Thanks!

B.R.
Vladimir
