### ISSUE TITLE
finetune on flyingthings3d

### ISSUE THREAD

**Issue by shanyuhu** [NVlabs/PWC-Net#9]
Hi, one question about the finetune on flyingthings3D.
Did you only use the "into_future_left", or all the combination "into_future_right", "into_past_left" and "into_past_right"?
Thanks for your answering.

**Comment by deqings** [comment]
We used the clean pass of all the combinations of left/right and future/past.

**Comment by JiamingSuen** [comment]
@luvegood @deqings Would you please comment on my last question? Thanks very much.
