### ISSUE TITLE
Moving to later Versions of PyTorch

### ISSUE THREAD

**Issue by NylaWorker** [NVlabs/PWC-Net#91]
Hello, 
I noticed that running on the latest PyTorch versions is not possible because `torch.utils.ffi` is deprecated. Are you planning to upgrade this? I saw the solution is moving to cpp, rather than c. How difficult do you think this would be?

Thank you!

**Comment by zhuangxiaopi** [comment]
+1

**Comment by NylaWorker** [comment]
Hello, I noticed your interested on the latest version. The way of doing so easily is by using the correlation layer found here: https://github.com/NVIDIA/flownet2-pytorch/tree/master/networks/correlation_package

This correlation layer is up to date and compatible to latest PyTorch! It does no longer use the deprecated PyTorch library.

**Comment by K1NSA** [comment]
> Hello, I noticed your interested on the latest version. The way of doing so easily is by using the correlation layer found here: https://github.com/NVIDIA/flownet2-pytorch/tree/master/networks/correlation_package
> 
> This correlation layer is up to date and compatible to latest PyTorch! It does no longer use the deprecated PyTorch library.


Hello, sorry to bother, should I just change the "correlation_package" with the files in Flownet2?  Does it need any installation?
