### ISSUE TITLE
About KITTI2015

### ISSUE THREAD

**Issue by MuZiGuYue** [NVlabs/PWC-Net#97]
Hello,
As far as I know, the KITTI2015 dataset is a data pair composed of two video frames. How do you apply it in a multi-frame converged network?
Thank you!

**Comment by luvegood** [comment]
@MuZiGuYue you can download all frames in the KITTI website

**Comment by MuZiGuYue** [comment]
Thank you for your reply:
For some reason, I can't enter the official website of the KITTI dataset right now.
Does the KITTI dataset contain the corresponding optical flow diagram?
Is the KITTI dataset the same as the virtual KITTI mentioned in the paper "A Fusion Approach for Multi-Frame Optical Flow Estimation"?
Thank you!

**Comment by MuZiGuYue** [comment]
@luvegood Thank you for your reply:
For some reason, I can't enter the official website of the KITTI dataset right now.
Does the KITTI dataset contain the corresponding optical flow diagram?
Is the KITTI dataset the same as the virtual KITTI mentioned in the paper "A Fusion Approach for Multi-Frame Optical Flow Estimation"?
Thank you!

**Comment by luvegood** [comment]
@MuZiGuYue you'll need to contact authors of KITTI dataset for help. I downloaded those images from the official KITTI website

**Comment by MuZiGuYue** [comment]
@luvegood Thank you very much!

**Comment by MuZiGuYue** [comment]
@luvegood 
Sorry to bother you again,
For the KITTI dataset, not all video frames have corresponding optical flow.
Even if I downloaded all the frames, there is no way to train the multi-frame fusion model with them.
Thanks again!

**Comment by luvegood** [comment]
@MuZiGuYue In KITTI we only use the preceding frame for training the multi-frame optical flow, and the only supervision signal in KITTI is the optical flow from the reference frame to the future frame. For other datasets, we use the full dataset for training MFF

**Comment by MuZiGuYue** [comment]
@luvegood Thank you very much for your help, I finally understood.
